### ISSUE TITLE
Codespace runs in recovery mode

### ISSUE THREAD

**Issue by enricorotundo** [davidgasquez/cod-playground#2]
<img width="544" alt="Screenshot 2023-01-19 at 10 28 56" src="https://user-images.githubusercontent.com/4340327/213405694-32781047-b3e5-40c9-9387-cb9e6a033a01.png">

```
2023-01-19 09:25:35.781Z: #11 ERROR: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: write /home/codespace/.local/lib/python3.10/site-packages/scipy/spatial/transform/_rotation.cpython-310-x86_64-linux-gnu.so: no space left on device
2023-01-19 09:25:35.891Z: ------
 > [dev_container_auto_added_stage_label 1/8] FROM mcr.microsoft.com/devcontainers/universal:linux@sha256:69347816325cd533990d5d821063ec1fee3b34676007cc3e1214edc8f5f9251f:
2023-01-19 09:25:35.895Z: ------
2023-01-19 09:25:35.921Z: ERROR: failed to solve: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: write /home/codespace/.local/lib/python3.10/site-packages/scipy/spatial/transform/_rotation.cpython-310-x86_64-linux-gnu.so: no space left on device2023-01-19 09:25:35.927Z: 
2023-01-19 09:25:36.011Z: {"outcome":"error","message":"Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.26.0-1674120182399/Dockerfile-with-features -t vsc-cod-playground-c3843f73768439cbef3a4c4a00095ade --target dev_containers_target_stage --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.26.0-1674120182399 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /var/lib/docker/codespacemount/workspace/cod-playground","description":"An error occurred building the image."}
2023-01-19 09:25:36.014Z: {"type":"stop","level":3,"timestamp":1674120335987,"text":"Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.26.0-1674120182399/Dockerfile-with-features -t vsc-cod-playground-c3843f73768439cbef3a4c4a00095ade --target dev_containers_target_stage --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.26.0-1674120182399 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /var/lib/docker/codespacemount/workspace/cod-playground","startTimestamp":1674120184007}
2023-01-19 09:25:36.020Z: Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.26.0-1674120182399/Dockerfile-with-features -t vsc-cod-playground-c3843f73768439cbef3a4c4a00095ade --target dev_containers_target_stage --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.26.0-1674120182399 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /var/lib/docker/codespacemount/workspace/cod-playground
2023-01-19 09:25:36.021Z:     at Zne (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1866:1635)
2023-01-19 09:25:36.025Z:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2023-01-19 09:25:36.027Z:     at async EF (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1865:1963)
2023-01-19 09:25:36.031Z:     at async x7 (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1865:901)
2023-01-19 09:25:36.034Z:     at async oie (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1871:2093)
2023-01-19 09:25:36.036Z:     at async qf (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1871:3239)
2023-01-19 09:25:36.041Z:     at async Mse (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1995:16211)
2023-01-19 09:25:36.044Z:     at async Lse (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1995:15965)
2023-01-19 09:25:36.052Z: devcontainer process exited with exit code 1

====================================== ERROR ====================================
2023-01-19 09:25:36.065Z: Failed to create container.
=================================================================================
2023-01-19 09:25:36.074Z: Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.26.0-1674120182399/Dockerfile-with-features -t vsc-cod-playground-c3843f73768439cbef3a4c4a00095ade --target dev_containers_target_stage --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.26.0-1674120182399 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /var/lib/docker/codespacemount/workspace/cod-playground
2023-01-19 09:25:36.076Z: Error Code: 1302

====================================== ERROR ====================================
2023-01-19 09:25:36.095Z: Container creation failed.
=================================================================================
2023-01-19 09:25:36.118Z: 

```

**Comment by davidgasquez** [comment]
I've pushed [some changes to make Codespaces ask for a bigger machine](https://github.com/davidgasquez/cod-playground/blob/5b1ab8925bc239a1465dfa446972e21db7778888/.devcontainer/devcontainer.json#L10). I ran out of Codespaces credit and can't test it out. Mind starting a new Codespace environment and see if this is still an issue?

**Comment by enricorotundo** [comment]
Awesome, no more recovery mode!
<img width="1200" alt="Screenshot 2023-01-24 at 10 02 04" src="https://user-images.githubusercontent.com/4340327/214250569-97bc2a10-df8b-4b74-932b-5c8be79c9d70.png">
